version: '3.8'

volumes:
  content:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./"

services:

  app:
    build:
      context: ./
    restart: always
    volumes:
      - "content:/app"
    depends_on:
      - sql
    ports:
      - "5000:5000"
      - "5001:5001"

  sql:
    image: postgres:alpine
    container_name: db
    # volumes:
    #    - dbdata:/var/lib/postgresql/data:z  # Persist storage
    ports:
      - "6379:6379"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      POSTGRES_DATABASE: netful
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped