version: '3.8'

services:

  app:
    build:
      context: ./
    command: "./app/scripts/prod.sh"
    restart: always
    depends_on:
      - sql
    ports:
      - "5000:5000"
      - "5001:5001"

  sql:
    image: postgres:alpine
    container_name: db
    # volumes:
    #    - dbdata:/var/lib/postgresql/data:z  # Persist storage
    ports:
      - "6379:6379"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      POSTGRES_DATABASE: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped